openapi: 3.1.0
info:
  description: Simple API for managing products
  title: Product API
  version: 1.0.0
servers:
- url: http://localhost:3000/api
paths:
  /products:
    get:
      operationId: getProducts
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
                type: array
          description: List all products
      summary: Get all products
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "201":
          description: Product created
      summary: Create a new product
      x-eov-operation-handler: controllers/DefaultController
  /products/{id}:
    delete:
      operationId: deleteProduct
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Product deleted
      summary: Delete a product by ID
      x-eov-operation-handler: controllers/DefaultController
    get:
      operationId: getProductById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: Product details
      summary: Get a product by ID
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: updateProduct
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "200":
          description: Product updated
      summary: Update a product by ID
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Product:
      example:
        price: 9.99
        name: Coffee Mug
        description: A nice ceramic mug for coffee lovers
        id: "123"
      properties:
        id:
          example: "123"
          type: string
        name:
          example: Coffee Mug
          type: string
        price:
          example: 9.99
          type: number
        description:
          example: A nice ceramic mug for coffee lovers
          type: string
      type: object
